
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.2.142:3306/test?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: test
    password: DuNiTGxr.2Qp5WcV

mybatis:
  type-aliases-package: xyz.hcworld.mybatis.pagedemo.entity
  mapper-locations: classpath*:/mapper/**Mapper.xml

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true